#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx pretty-quick --staged

EMAIL=$(git config user.email)
if echo "$EMAIL" | grep -q "@users.noreply.github.com" > /dev/null
then
  echo "Email is correctly configured.";
else
  echo "Email is not configured to use accolades account";
  echo "run:"
  echo '   git config user.email "your-name@accolades.io"'
  echo ''
  exit 1; # 3)
fi;

